# overrides to create a testable deployment of the strategy market
name = "fx-strategy-market"
version = "<%= package.version %>-testable"
description = "Strategy market implementation"

[setting.owner]
description = "strategy market owner"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.synthetixPackage]
defaultValue = "polynomial-core:3.9.8-testable"
depends = []

[setting.salt]
defaultValue = "polynomial"

[import.synthetix]
source = "<%= settings.synthetixPackage %>"

[contract.StrategyMarketFactoryModule]
artifact = "StrategyMarketFactoryModule"

[contract.ProfitShareModule]
artifact = "ProfitShareModule"

[contract.CoreModule]
artifact = "contracts/modules/CoreModule.sol:CoreModule"

[contract.InitialStrategyMarketProxy]
artifact = "contracts/Proxy.sol:Proxy"
args = ["<%= contracts.CoreModule.address %>", "<%= settings.owner %>"]
abiOf = ["CoreModule"]
salt = "<%= settings.salt %>"

# Core
[router.StrategyMarketRouter]
contracts = ["CoreModule", "StrategyMarketFactoryModule", "ProfitShareModule"]

[invoke.upgradeStrategyMarketProxy]
target = ["InitialStrategyMarketProxy"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.StrategyMarketRouter.address %>"]
factory.StrategyMarketProxy.artifact = "contracts/Proxy.sol:Proxy"
factory.StrategyMarketProxy.abiOf = ["StrategyMarketRouter"]
factory.StrategyMarketProxy.event = "Upgraded"
factory.StrategyMarketProxy.arg = 0
factory.StrategyMarketProxy.highlight = true

# add pool owner to feature flag allow list
[invoke.addStrategyMarketToFeatureFlag]
target = ["synthetix.CoreProxy"]
func = "addToFeatureFlagAllowlist"
from = "<%= settings.owner %>"
args = [
    "0x72656769737465724d61726b6574000000000000000000000000000000000000",
    "<%= contracts.StrategyMarketProxy.address %>",
] # formatBytes32String("registerMarket")

[invoke.setSynthetixSystem]
target = ["StrategyMarketProxy"]
from = "<%= settings.owner %>"
func = "setSynthetix"
args = ["<%= imports.synthetix.contracts.CoreProxy.address %>"]
